### ISSUE TITLE
Option to exclude scenes with a specific tag from search

### ISSUE THREAD

**Issue by com1234475** [com1234475/stash-plugin-performer-creator#1]
When preforming the search allow the option to exclude scene based on tags.

**Comment by JoeSmithStarkers** [comment]
Hi are you asking for this feature?

![image](https://user-images.githubusercontent.com/60503487/95004377-1b3e4b00-0636-11eb-84d6-818704f88b89.png)

**Comment by Tweeticoats** [comment]
Can you also exclude everything with a scene url.
Anything with a scene url has most likely been correctly matched and scraped so do not need to be processed.

**Comment by com1234475** [comment]
Done for both
