### ISSUE TITLE
New spacy version released is incompatible with plugin

### ISSUE THREAD

**Issue by andbigdata** [com1234475/stash-plugin-performer-creator#4]
Need to either specify spacy version 2.3.5 install or update code to reflect the changes in spacy.

This was the result of installing spacy without giving the version number.

21-02-03 01:34:59
Error   
Plugin returned error: exit status 1
2021-02-03 01:34:59
Error   
[Plugin]     raise IOError(Errors.E053.format(path=config_path, name="config.cfg"))
2021-02-03 01:34:59
Error   
[Plugin]   File "/usr/local/lib/python3.8/dist-packages/spacy/util.py", line 545, in load_config
2021-02-03 01:34:59
Error   
[Plugin]     config = load_config(config_path, overrides=dict_to_dot(config))
2021-02-03 01:34:59
Error   
[Plugin]   File "/usr/local/lib/python3.8/dist-packages/spacy/util.py", line 388, in load_model_from_path
2021-02-03 01:34:59
Error   
[Plugin]     return load_model_from_path(Path(name), **kwargs)
2021-02-03 01:34:59
Error   
[Plugin]   File "/usr/local/lib/python3.8/dist-packages/spacy/util.py", line 324, in load_model
2021-02-03 01:34:59
Error   
[Plugin]     return util.load_model(name, disable=disable, exclude=exclude, config=config)
2021-02-03 01:34:59
Error   
[Plugin]   File "/usr/local/lib/python3.8/dist-packages/spacy/__init__.py", line 47, in load
2021-02-03 01:34:59
Error   
[Plugin]     nlp = spacy.load(model)
2021-02-03 01:34:59
Error   
[Plugin]   File "/root/.stash/plugins/performer_creator.py", line 17, in <module>
2021-02-03 01:34:59
Error   
[Plugin] OSError: [E053] Could not read config.cfg from /root/.stash/plugins/ner_model/config.cfg
2021-02-03 01:34:59
Error   
[Plugin] /usr/local/lib/python3.8/dist-packages/spacy/util.py:715: UserWarning: [W094] Model 'en_model' (0.0.0) specifies an under-constrained spaCy version requirement: >=2.3.2. This can lead to compatibility problems with older versions, or as new spaCy versions are released, because the model may say it's compatible when it's not. Consider changing the "spacy_version" in your meta.json to a version range, with a lower and upper pin. For example: >=3.0.1,<3.1.0
2021-02-03 01:34:59
Error   
[Plugin] Traceback (most recent call last):
2021-02-03 01:34:59
Error   
[Plugin]   warnings.warn(warn_msg)
2021-02-03 01:14:47
Error   
Plugin returned error: exit status 1

To get the plugin working again for me I had to do:
pip install spacy==2.3.5

and then:
python -m spacy download en_core_web_md

**Comment by com1234475** [comment]
Thanks @andbigdata, Ive pinned the package
