### ISSUE TITLE
any guide on how to get this setup in Unraid?

### ISSUE THREAD

**Issue by heezy01** [com1234475/stash-plugin-performer-creator#5]
i have Unraid 6.9.1 setup with stash docker and i am trying to use this plugin, but i am not sure how to setup a virtualenv in unraid. do i use the stash docker's console or Unraid's terminal?

the error i get in stash is, "Error running plugin task: Error running plugin: fork/exec /root/.stash/plugins/env/bin/python: no such file or directory"

any help to set this up in Unraid? thanks!

**Comment by sbaak12** [comment]
This is just my experience.. hopefully something here can lead you down the right path. 
Use a normal ssh session to your unraid server. or if you really want then use the webui to get to stash's console and start at the second line.
```
docker exec -i -t Stash bash
apt-get update
apt-get install virtualenv
virtualenv -p python3 --system-site-packages /root/.stash/plugins/env
source /root/.stash/plugins/env/bin/activate
python -m pip install spacy==2.3.5
python -m pip install requests
python -m spacy download en_core_web_md
```

`docker ps` if the name Stash is wrong 'could be lowercase s or whatever'

**Comment by heezy01** [comment]
i got this to work using Unraid's terminal and started on line one. for the plugin to work, the files have to be in the root of the plugins folder. in Unraid, it is located in appdata\stash\config\plugins. now the plugin looks like it is working so far. thank you!

**Comment by sbaak12** [comment]
np. 
ya i didn't include getting the plugin there. ill write it out incase anyone finds this later.
```
# after apt-get update
apt-get install git
cd /root/.stash/plugins/
git clone https://github.com/com1234475/stash-plugin-performer-creator.git
```

**Comment by com1234475** [comment]
thanks @sbaak12 , I've added your guide to the read me.
